sudo: required
services:
  - docker

before_install:
  - docker build -t drout/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true drout/react-test npm test 

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker

  #Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login docker.io -u "$DOCKER_ID" --password-stdin
  
  #Take images from above and push them to Docker Hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker

  # deploy:
  #   provider: elasticbeanstalk
  #   region: <sub-domain present in aws url>
  #   app: multi-docker
  #   env: MultiDocker-env
  #   bucket_name: <search s3 and then your sub-domain, then open the sub-domain>
  #   bucket_path: docker-multi
  #   on:
  #     branch: master
  #   access_key_id: $AWS_ACCESS_KEY
  #   secret_access_key:
  #     secure: $AWS_SECRET_KEY
